### ISSUE TITLE
Error in bind mounting - Loss of permanency

### ISSUE THREAD

**Issue by Eirikr70** [aguslr/docker-findmydeviceserver#5]
Hello, I have set up docker-findmydeviceserver a while ago and I have noticed that the registration of my device was temporary. As soon as I restarted the container, I had to registrate it again. That seems to be related to bind mounting the `/data` repertory of the container whereas the `/fmd` repository should be mounted.
This poses another problem since the `config.yml` is also mounted in the same repository. I think it should be placed somewhere else in the container.
There are workarounds but you have to first start the container with `config.yml` bind mount, then copy the content of `/fmd` repertory, then unmount `config.yml` and mount `/fmd`.

**Comment by aguslr** [comment]
It seems that, for [v0.5.0][1],`./data` should be [mounted to `/fmd/objectbox/`][2] instead:

    docker run -p 8080:8080 -v "${PWD}"/data:/fmd/objectbox \
         docker.io/aguslr/findmydeviceserver:latest

Please, confirm persistence works so I can merge the PR and close the issue. Thanks!

[1]: https://gitlab.com/Nulide/findmydeviceserver/-/releases/v0.5.0
[2]: https://gitlab.com/Nulide/findmydeviceserver/-/tree/ed94007057356326d379dd35c179798b1c5b0706#self-hosting-with-docker-compose

**Comment by Eirikr70** [comment]
I confirm and am grateful to you for the support.
Thanks
